[build]
  command = "npx prisma generate && npx prisma db push && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_DISABLE_ESLINT = "1"
  NEXT_DISABLE_TYPECHECK = "1"
